name: Build images

on:
  push:
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/main.yml'
  schedule:
    - cron: '12 2 * * MON'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY_NAMESPACE: sonal123890  # Your Docker Hub username
  IMAGE_REPOSITORY: alfresco-base-java

jobs:
  build:
    name: Java ${{ matrix.java_major }} on ${{ matrix.base_image.flavor }}:${{ matrix.base_image.major }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.ref_name == 'master' && false || true }}
      matrix:
        base_image:
          - flavor: rockylinux
            major: 8
          - flavor: rockylinux
            major: 9
        java_major:
          - 11
          - 17
          - 21
        jdist:
          - jre
        exclude:
          - base_image:
              flavor: rockylinux
              major: 9
            java_major: 11
          - base_image:
              flavor: rockylinux
              major: 8
            java_major: 21
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: vars
        name: Compute Image Tag
        env:
          IMAGE_BASE_NAME: ${{ matrix.jdist }}${{ matrix.java_major }}-${{ matrix.base_image.flavor }}${{ matrix.base_image.major }}
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "image_tag=$IMAGE_BASE_NAME" >> $GITHUB_OUTPUT
            echo "image_labels=" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${IMAGE_BASE_NAME}-${GITHUB_REF_NAME//\//-}" >> $GITHUB_OUTPUT
            echo "image_labels=quay.expires-after=2w" >> $GITHUB_OUTPUT
          fi
          echo "image_created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "timestamp=$(date -u +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      # Docker login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username (stored in GitHub Secrets)
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or token (stored in GitHub Secrets)

      - name: Build Image locally
        uses: docker/build-push-action@v2
        with:
          load: true
          build-args: |
            JDIST=${{ matrix.jdist }}
            DISTRIB_NAME=${{ matrix.base_image.flavor }}
            DISTRIB_MAJOR=${{ matrix.base_image.major }}
            JAVA_MAJOR=${{ matrix.java_major }}
            REVISION=${{ github.run_number }}
            CREATED=${{ steps.vars.outputs.image_created }}
          tags: |
            ${{ env.IMAGE_REGISTRY_NAMESPACE }}/${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}
          target: JAVA_BASE_IMAGE

      - name: Test Built Image
        run: |
          echo -n "Checking for java version: "
          docker run ${{ env.IMAGE_REGISTRY_NAMESPACE }}/${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.image_tag }} java -version 2>&1 \
          | grep -i 'version \"${{ matrix.java_major }}\.'
          echo -n "Checking shell environment: "
          BASH_LOGIN="$(docker run ${{ env.IMAGE_REGISTRY_NAMESPACE }}/${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.image_tag }} /bin/bash 2>&1 > /dev/null || true)"
          if [ -z "$BASH_LOGIN" ]; then
            echo ok
          else echo 'bash reported an error'
            echo $BASH_LOGIN
            exit 7

      # Push images to Docker Hub
      - name: Push images to Docker Hub
        run: |
          docker push ${{ env.IMAGE_REGISTRY_NAMESPACE }}/${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}
          docker push ${{ env.IMAGE_REGISTRY_NAMESPACE }}/${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}-${{ steps.vars.outputs.timestamp }}
